### ISSUE TITLE
Collaboration Perms

### ISSUE THREAD

**Issue by TolleyB-J** [jesusgn90/bar-commander#15]
Please can you add me as a collaborator I am TolleyB-J from the reddit post https://www.reddit.com/r/node/comments/96ffcf/restaurant_management_system/

**Comment by jesusgn90** [comment]
That's not the way you can collaborate, please take a look into our https://github.com/jesusgn90/bar-commander/blob/master/CONTRIBUTING.md doc, there you'll see how to collaborate. Thanks in advance
